name: 'Set package.json version'
description: 'Set the version in package.json'
branding:
  icon: 'arrow-up-circle'
  color: 'red'
inputs:
  version:
    description: 'Version to create, eg, 5.11.2'
    required: true
  path:
    description: 'Path to package.json file'
    default: .
  validate:
    description: 'Validate version according to SemVer rules'
    default: true
runs:
  using: 'node12'
  main: 'index.js'

